-- MySQL Script generated by MySQL Workbench
-- 12/03/14 23:49:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbcarlos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbcarlos` ;

-- -----------------------------------------------------
-- Schema dbcarlos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcarlos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbcarlos` ;

-- -----------------------------------------------------
-- Table `dbcarlos`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Endereco` (
  `codigoEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigoEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Funcionario` (
  `codigoFuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nivel` TINYINT(1) NOT NULL,
  `codigoEndereco` INT NOT NULL,
  PRIMARY KEY (`codigoFuncionario`, `codigoEndereco`),
  INDEX `fk_Funcionario_Endereco1_idx` (`codigoEndereco` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Administrador` (
  `Funcionario_codigoFuncionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Funcionario_codigoFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Usuario` (
  `Funcionario_codigoFuncionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Funcionario_codigoFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Cliente` (
  `codigoCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  `mensalista` TINYINT(1) NOT NULL,
  `codigoEndereco` INT NOT NULL,
  PRIMARY KEY (`codigoCliente`, `codigoEndereco`),
  INDEX `fk_Cliente_Endereco1_idx` (`codigoEndereco` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Veiculo` (
  `placa` VARCHAR(10) NOT NULL,
  `cor` VARCHAR(10) NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `porte` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `codigoCliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`placa`, `codigoCliente`),
  INDEX `fk_Veiculo_Cliente1_idx` (`codigoCliente` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`DadosEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`DadosEmpresa` (
  `cnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `ie` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `codigoEndereco` INT NOT NULL,
  PRIMARY KEY (`cnpj`, `codigoEndereco`),
  INDEX `fk_DadosEmpresa_Endereco_idx` (`codigoEndereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcarlos`.`Cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`Cupom` (
  `codigoCupom` INT NOT NULL AUTO_INCREMENT,
  `horaEntrada` DATETIME NOT NULL,
  `horaSaida` DATETIME NOT NULL,
  `data` DATETIME NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `total` FLOAT NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `codigoFuncionario` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoCupom`, `placa`),
  INDEX `fk_Cupom_Funcionario1_idx` (`codigoFuncionario` ASC),
  INDEX `fk_Cupom_DadosEmpresa1_idx` (`cnpj` ASC))
ENGINE = InnoDB;

USE `dbcarlos` ;

-- -----------------------------------------------------
-- Placeholder table for view `dbcarlos`.`consuempresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`consuempresa` (`cnpj` INT, `telefone` INT, `ie` INT, `nomeFantasia` INT, `codigoEndereco` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dbcarlos`.`preeempresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcarlos`.`preeempresa` (`nomeFantasia` INT, `ie` INT, `telefone` INT, `cnpj` INT, `cep` INT, `logradouro` INT, `numero` INT, `complemento` INT, `bairro` INT, `cidade` INT, `estado` INT);

-- -----------------------------------------------------
-- View `dbcarlos`.`consuempresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcarlos`.`consuempresa`;
USE `dbcarlos`;
Create  OR REPLACE View `consuempresa` AS SELECT `cnpj`, `telefone`, `ie`, `nomeFantasia`, `codigoEndereco` FROM `dadosempresa`;

-- -----------------------------------------------------
-- View `dbcarlos`.`preeempresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcarlos`.`preeempresa`;
USE `dbcarlos`;
CREATE  OR REPLACE VIEW `preeempresa` AS SELECT `nomeFantasia`, `ie`, `telefone`, `cnpj`, `cep`, `logradouro`, `numero`, `complemento`, `bairro`, `cidade`, `estado` FROM `dadosempresa` AS `d`, `endereco` AS `e` WHERE `d`.`codigoEndereco` = `e`.`codigoEndereco`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
